CREATE TABLE [dbo].[tempFixedFilterSegmentationCriteria]
(
[Priority] [int] NULL,
[Fixed Filter Segment] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Filter Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Loan Purpose] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Occupancy] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Min FICO] [float] NULL,
[Max FICO] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Self-Graded Credit] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Min LTV] [float] NULL,
[Max LTV] [float] NULL,
[Min Loan Amt] [float] NULL,
[Max Loan Amt] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Units] [float] NULL,
[Property Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BK] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Foreclose] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Segment Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConformingFlag] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JumboFlag] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FHAFlag] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubPrimeFlag] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CashoutFlag] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MortgageClassLookup] [int] NULL,
[BankruptcyYearsBack] [int] NULL,
[ForeclosureYearsBack] [int] NULL,
[PropertyUseLookup] [int] NULL,
[MaxFICO] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaxLoanAmount] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FHALimitCap] [int] NULL,
[PropertyTypeLookup] [int] NULL,
[MaxLoanAmountConverted] [int] NULL,
[MaxFICOConverted] [int] NULL
) ON [PRIMARY]
GO
