CREATE TABLE [dbo].[tempFixedFiltersQFormSegmentation_old]
(
[QFormID] [int] NOT NULL,
[LTLIndicator] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReferralCount] [int] NULL,
[TotalMatchFee] [numeric] (9, 2) NULL,
[BorrowerID] [int] NOT NULL,
[ProductTypeLookup] [int] NOT NULL,
[AmountRequested] [decimal] (11, 2) NOT NULL,
[PropertyUseLookup] [int] NOT NULL,
[PropertyTypeLookup] [int] NOT NULL,
[DwellingUnits] [smallint] NULL,
[MortgageClassLookup] [int] NOT NULL,
[RefiCashoutFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZipCode] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[County] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ForeclosureDate] [datetime] NULL,
[BankruptcyDate] [datetime] NULL,
[LTV] [decimal] (9, 2) NULL,
[CreditScore] [int] NULL,
[StatedCreditHistory] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GSELimit1LivingUnit] [int] NULL,
[FHALimit1LivingUnit] [int] NULL,
[SegmentName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FHAEligibleFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FHAJumboEligibleFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ConformingEligibleFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ConformingJumboEligibleFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[JumboEligibleFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[QFCompleteDate] [datetime] NOT NULL,
[MarketPlacePartnerName] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
