CREATE TABLE [dbo].[tempFixedFiltersQFormSegmentation]
(
[QFormID] [int] NOT NULL,
[LTLIndicator] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReferralCount] [int] NULL,
[TotalMatchFee] [numeric] (9, 2) NULL,
[BorrowerID] [int] NOT NULL,
[ProductTypeLookup] [int] NOT NULL,
[AmountRequested] [decimal] (11, 2) NOT NULL,
[PropertyUseLookup] [int] NOT NULL,
[PropertyTypeLookup] [int] NOT NULL,
[DwellingUnits] [smallint] NULL,
[MortgageClassLookup] [int] NOT NULL,
[RefiCashoutFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZipCode] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[County] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ForeclosureDate] [datetime] NULL,
[BankruptcyDate] [datetime] NULL,
[LTV] [decimal] (9, 2) NULL,
[CreditScore] [int] NULL,
[StatedCreditHistory] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GSELimit1LivingUnit] [int] NULL,
[FHALimit1LivingUnit] [int] NULL,
[SegmentName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FHAEligibleFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tempFixed__FHAEl__4A041FA3] DEFAULT ('N'),
[FHAJumboEligibleFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tempFixed__FHAJu__4AF843DC] DEFAULT ('N'),
[ConformingEligibleFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tempFixed__Confo__4BEC6815] DEFAULT ('N'),
[ConformingJumboEligibleFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tempFixed__Confo__4CE08C4E] DEFAULT ('N'),
[JumboEligibleFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tempFixed__Jumbo__4DD4B087] DEFAULT ('N'),
[QFCompleteDate] [datetime] NOT NULL,
[MarketPlacePartnerName] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FundedFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SegmentFilterID] [int] NOT NULL,
[SegmentFilterName] [varchar] (96) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
