IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'DS1\sKhan')
CREATE LOGIN [DS1\sKhan] FROM WINDOWS
GO
CREATE USER [DS1\sKhan] FOR LOGIN [DS1\sKhan] WITH DEFAULT_SCHEMA=[DS1\sKhan]
GO
REVOKE CONNECT TO [DS1\sKhan]
